// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Area struct {
	ID       int64  `json:"id"`
	AreaName string `json:"area_name"`
	AreaDesc string `json:"area_desc"`
}

type Band struct {
	ID        int64  `json:"id"`
	BandName  string `json:"band_name"`
	BandDesc  string `json:"band_desc"`
	Size      int64  `json:"size"`
	StartFreq int64  `json:"start_freq"`
	EndFreq   int64  `json:"end_freq"`
	TechID    int64  `json:"tech_id"`
}

type Block struct {
	ID              int64  `json:"id"`
	BlockName       string `json:"block_name"`
	BlockDesc       string `json:"block_desc"`
	TotalPopulation int64  `json:"total_population"`
	TownID          int64  `json:"town_id"`
	ClutterID       int64  `json:"clutter_id"`
}

type Carrier struct {
	ID          int64  `json:"id"`
	CarrierName string `json:"carrier_name"`
	CarrierDesc string `json:"carrier_desc"`
	Size        int64  `json:"size"`
	StartFreq   int64  `json:"start_freq"`
	EndFreq     int64  `json:"end_freq"`
	BandID      int64  `json:"band_id"`
}

type Cell struct {
	ID                int64  `json:"id"`
	CellName          string `json:"cell_name"`
	CellNameOld       string `json:"cell_name_old"`
	CellIDGivin       string `json:"cell_id_givin"`
	CellIDGivinOld    string `json:"cell_id_givin_old"`
	SectorName        string `json:"sector_name"`
	Uplinkuarfcn      string `json:"uplinkuarfcn"`
	Downlinkuarfcn    string `json:"downlinkuarfcn"`
	Dlprscramblecode  string `json:"dlprscramblecode"`
	Azimuth           string `json:"azimuth"`
	Height            string `json:"height"`
	Etilt             string `json:"etilt"`
	Mtilt             string `json:"mtilt"`
	Antennatype       string `json:"antennatype"`
	Antennamodel      string `json:"antennamodel"`
	Ecgi              string `json:"ecgi"`
	SiteID            int64  `json:"site_id"`
	CarrierID         int64  `json:"carrier_id"`
	ServiceareatypeID int64  `json:"serviceareatype_id"`
}

type City struct {
	ID       int64  `json:"id"`
	CityName string `json:"city_name"`
	CityDesc string `json:"city_desc"`
	StateID  int64  `json:"state_id"`
}

type Clutter struct {
	ID          int64  `json:"id"`
	ClutterName string `json:"clutter_name"`
	ClutterDesc string `json:"clutter_desc"`
}

type Continent struct {
	ID            int64  `json:"id"`
	ContinentName string `json:"continent_name"`
	ContinentDesc string `json:"continent_desc"`
}

type Country struct {
	ID          int64  `json:"id"`
	CountryName string `json:"country_name"`
	CountryDesc string `json:"country_desc"`
	ContinentID int64  `json:"continent_id"`
}

type District struct {
	ID           int64  `json:"id"`
	DistrictName string `json:"district_name"`
	DistrictDesc string `json:"district_desc"`
	CityID       int64  `json:"city_id"`
}

type Property struct {
	ID           int64   `json:"id"`
	PropertyName string  `json:"property_name"`
	Lat          float32 `json:"lat"`
	Long         float32 `json:"long"`
	BlockID      int64   `json:"block_id"`
}

type Serviceareatype struct {
	ID                  int64  `json:"id"`
	ServiceareatypeName string `json:"serviceareatype_name"`
	ServiceareatypeDesc string `json:"serviceareatype_desc"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Site struct {
	ID             int64     `json:"id"`
	SiteName       string    `json:"site_name"`
	SiteNameOld    string    `json:"site_name_old"`
	SiteIDGivin    string    `json:"site_id_givin"`
	SiteIDGivinOld string    `json:"site_id_givin_old"`
	Lac            string    `json:"lac"`
	Rac            string    `json:"rac"`
	Rnc            string    `json:"rnc"`
	SiteOnAirDate  time.Time `json:"site_on_air_date"`
	PropertyID     int64     `json:"property_id"`
	SitetypeID     int64     `json:"sitetype_id"`
	VendorID       int64     `json:"vendor_id"`
}

type Sitetype struct {
	ID       int64  `json:"id"`
	TypeName string `json:"type_name"`
	TypeDesc string `json:"type_desc"`
}

type State struct {
	ID        int64  `json:"id"`
	StateName string `json:"state_name"`
	StateDesc string `json:"state_desc"`
	CountryID int64  `json:"country_id"`
	AreaID    int64  `json:"area_id"`
}

type Tech struct {
	ID       int64  `json:"id"`
	TechName string `json:"tech_name"`
	TechDesc string `json:"tech_desc"`
}

type Town struct {
	ID         int64  `json:"id"`
	TownName   string `json:"town_name"`
	TownDesc   string `json:"town_desc"`
	DistrictID int64  `json:"district_id"`
}

type Traffic struct {
	ID                       int64     `json:"id"`
	TrafficDate              time.Time `json:"traffic_date"`
	Avgdailydldatamb         float32   `json:"avgdailydldatamb"`
	Avgdailyuldatamb         float32   `json:"avgdailyuldatamb"`
	Avgdailytotdatamb        float32   `json:"avgdailytotdatamb"`
	Avgdailytotvoicemin      float32   `json:"avgdailytotvoicemin"`
	Avgdailytotvideomin      float32   `json:"avgdailytotvideomin"`
	Qci1Data                 float32   `json:"qci1_data"`
	Qci6Data                 float32   `json:"qci6_data"`
	Qci8Data                 float32   `json:"qci8_data"`
	QciOtherData             float32   `json:"qci_other_data"`
	Avgdailytotvoicemin4g    float32   `json:"avgdailytotvoicemin4g"`
	Avgdailytotvoicemintotal float32   `json:"avgdailytotvoicemintotal"`
	Userdlthroughput         float32   `json:"userdlthroughput"`
	Dlpacketlossrate         float32   `json:"dlpacketlossrate"`
	Overallpsdropcallrate    float32   `json:"overallpsdropcallrate"`
	Bhdldatamb               float32   `json:"bhdldatamb"`
	Bhupdatamb               float32   `json:"bhupdatamb"`
	Bhtotdatamb              float32   `json:"bhtotdatamb"`
	Bhtotvoicemin            float32   `json:"bhtotvoicemin"`
	Bhtotvideomin            float32   `json:"bhtotvideomin"`
	Bhcsusers                float32   `json:"bhcsusers"`
	Bhhsupausers             float32   `json:"bhhsupausers"`
	Bhhsdpausers             float32   `json:"bhhsdpausers"`
	Bhr99uldl                float32   `json:"bhr99uldl"`
	Powercapacity            float32   `json:"powercapacity"`
	Powerutilization         float32   `json:"powerutilization"`
	Codecapacity             float32   `json:"codecapacity"`
	Codeutilization          float32   `json:"codeutilization"`
	Ceulcapacity             float32   `json:"ceulcapacity"`
	Ceulutilization          float32   `json:"ceulutilization"`
	Cedlcapacity             float32   `json:"cedlcapacity"`
	Cedlutilization          float32   `json:"cedlutilization"`
	Iubcapacity              float32   `json:"iubcapacity"`
	Iubutlization            float32   `json:"iubutlization"`
	Bhrrcusers               float32   `json:"bhrrcusers"`
	CellID                   int64     `json:"cell_id"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	PasswordCreatedAt time.Time `json:"password_created_at"`
	Role              string    `json:"role"`
}

type Vendor struct {
	ID         int64  `json:"id"`
	VendorName string `json:"vendor_name"`
	VendorDesc string `json:"vendor_desc"`
}
