// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateArea(ctx context.Context, arg CreateAreaParams) (Area, error)
	CreateBand(ctx context.Context, arg CreateBandParams) (Band, error)
	CreateBlock(ctx context.Context, arg CreateBlockParams) (Block, error)
	CreateCarrier(ctx context.Context, arg CreateCarrierParams) (Carrier, error)
	CreateCell(ctx context.Context, arg CreateCellParams) (Cell, error)
	CreateCity(ctx context.Context, arg CreateCityParams) (City, error)
	CreateClutter(ctx context.Context, arg CreateClutterParams) (Clutter, error)
	CreateContinent(ctx context.Context, arg CreateContinentParams) (Continent, error)
	CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error)
	CreateDistrict(ctx context.Context, arg CreateDistrictParams) (District, error)
	CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error)
	CreateServiceareatype(ctx context.Context, arg CreateServiceareatypeParams) (Serviceareatype, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	CreateSitetype(ctx context.Context, arg CreateSitetypeParams) (Sitetype, error)
	CreateState(ctx context.Context, arg CreateStateParams) (State, error)
	CreateTech(ctx context.Context, arg CreateTechParams) (Tech, error)
	CreateTown(ctx context.Context, arg CreateTownParams) (Town, error)
	CreateTraffic(ctx context.Context, arg CreateTrafficParams) (Traffic, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error)
	DeleteArea(ctx context.Context, id int64) error
	DeleteBand(ctx context.Context, id int64) error
	DeleteBlock(ctx context.Context, id int64) error
	DeleteCarrier(ctx context.Context, id int64) error
	DeleteCell(ctx context.Context, id int64) error
	DeleteCity(ctx context.Context, id int64) error
	DeleteClutter(ctx context.Context, id int64) error
	DeleteContinent(ctx context.Context, id int64) error
	DeleteCountry(ctx context.Context, id int64) error
	DeleteDistrict(ctx context.Context, id int64) error
	DeleteProperty(ctx context.Context, id int64) error
	DeleteServiceareatype(ctx context.Context, id int64) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSite(ctx context.Context, id int64) error
	DeleteSitetype(ctx context.Context, id int64) error
	DeleteState(ctx context.Context, id int64) error
	DeleteTech(ctx context.Context, id int64) error
	DeleteTown(ctx context.Context, id int64) error
	DeleteTraffic(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, username string) error
	DeleteVendor(ctx context.Context, id int64) error
	GetArea0(ctx context.Context, id int64) (Area, error)
	GetArea1(ctx context.Context, areaName string) (Area, error)
	GetBand0(ctx context.Context, id int64) (Band, error)
	GetBand1(ctx context.Context, bandName string) (Band, error)
	GetBlock0(ctx context.Context, id int64) (Block, error)
	GetBlock1(ctx context.Context, blockName string) (Block, error)
	GetCarrier0(ctx context.Context, id int64) (Carrier, error)
	GetCarrier1(ctx context.Context, carrierName string) (Carrier, error)
	GetCell0(ctx context.Context, id int64) (Cell, error)
	GetCell1(ctx context.Context, cellName string) (Cell, error)
	GetCity0(ctx context.Context, id int64) (City, error)
	GetCity1(ctx context.Context, cityName string) (City, error)
	GetClutter0(ctx context.Context, id int64) (Clutter, error)
	GetClutter1(ctx context.Context, clutterName string) (Clutter, error)
	GetContinent0(ctx context.Context, id int64) (Continent, error)
	GetContinent1(ctx context.Context, continentName string) (Continent, error)
	GetCountry0(ctx context.Context, id int64) (Country, error)
	GetCountry1(ctx context.Context, countryName string) (Country, error)
	GetDistrict0(ctx context.Context, id int64) (District, error)
	GetDistrict1(ctx context.Context, districtName string) (District, error)
	GetProperty0(ctx context.Context, id int64) (Property, error)
	GetProperty1(ctx context.Context, propertyName string) (Property, error)
	GetServiceareatype0(ctx context.Context, id int64) (Serviceareatype, error)
	GetServiceareatype1(ctx context.Context, serviceareatypeName string) (Serviceareatype, error)
	GetSession0(ctx context.Context, id uuid.UUID) (Session, error)
	GetSite0(ctx context.Context, id int64) (Site, error)
	GetSite1(ctx context.Context, siteName string) (Site, error)
	GetSitetype0(ctx context.Context, id int64) (Sitetype, error)
	GetSitetype1(ctx context.Context, typeName string) (Sitetype, error)
	GetState0(ctx context.Context, id int64) (State, error)
	GetState1(ctx context.Context, stateName string) (State, error)
	GetTech0(ctx context.Context, id int64) (Tech, error)
	GetTech1(ctx context.Context, techName string) (Tech, error)
	GetTown0(ctx context.Context, id int64) (Town, error)
	GetTown1(ctx context.Context, townName string) (Town, error)
	GetTraffic0(ctx context.Context, id int64) (Traffic, error)
	GetUser0(ctx context.Context, username string) (User, error)
	GetUser3(ctx context.Context, email string) (User, error)
	GetVendor0(ctx context.Context, id int64) (Vendor, error)
	GetVendor1(ctx context.Context, vendorName string) (Vendor, error)
	ListAreas(ctx context.Context, arg ListAreasParams) ([]Area, error)
	ListBands(ctx context.Context, arg ListBandsParams) ([]Band, error)
	ListBlocks(ctx context.Context, arg ListBlocksParams) ([]Block, error)
	ListCarriers(ctx context.Context, arg ListCarriersParams) ([]Carrier, error)
	ListCells(ctx context.Context, arg ListCellsParams) ([]Cell, error)
	ListCities(ctx context.Context, arg ListCitiesParams) ([]City, error)
	ListClutters(ctx context.Context, arg ListCluttersParams) ([]Clutter, error)
	ListContinents(ctx context.Context, arg ListContinentsParams) ([]Continent, error)
	ListCountries(ctx context.Context, arg ListCountriesParams) ([]Country, error)
	ListDistricts(ctx context.Context, arg ListDistrictsParams) ([]District, error)
	ListProperties(ctx context.Context, arg ListPropertiesParams) ([]Property, error)
	ListServiceareatypes(ctx context.Context, arg ListServiceareatypesParams) ([]Serviceareatype, error)
	ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error)
	ListSites(ctx context.Context, arg ListSitesParams) ([]Site, error)
	ListSitetypes(ctx context.Context, arg ListSitetypesParams) ([]Sitetype, error)
	ListStates(ctx context.Context, arg ListStatesParams) ([]State, error)
	ListTechs(ctx context.Context, arg ListTechsParams) ([]Tech, error)
	ListTowns(ctx context.Context, arg ListTownsParams) ([]Town, error)
	ListTraffic(ctx context.Context, arg ListTrafficParams) ([]Traffic, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListVendors(ctx context.Context, arg ListVendorsParams) ([]Vendor, error)
	UpdateArea(ctx context.Context, arg UpdateAreaParams) (Area, error)
	UpdateBand(ctx context.Context, arg UpdateBandParams) (Band, error)
	UpdateBlock(ctx context.Context, arg UpdateBlockParams) (Block, error)
	UpdateCarrier(ctx context.Context, arg UpdateCarrierParams) (Carrier, error)
	UpdateCell(ctx context.Context, arg UpdateCellParams) (Cell, error)
	UpdateCity(ctx context.Context, arg UpdateCityParams) (City, error)
	UpdateClutter(ctx context.Context, arg UpdateClutterParams) (Clutter, error)
	UpdateContinent(ctx context.Context, arg UpdateContinentParams) (Continent, error)
	UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error)
	UpdateDistrict(ctx context.Context, arg UpdateDistrictParams) (District, error)
	UpdateProperty(ctx context.Context, arg UpdatePropertyParams) (Property, error)
	UpdateServiceareatype(ctx context.Context, arg UpdateServiceareatypeParams) (Serviceareatype, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error)
	UpdateSitetype(ctx context.Context, arg UpdateSitetypeParams) (Sitetype, error)
	UpdateState(ctx context.Context, arg UpdateStateParams) (State, error)
	UpdateTech(ctx context.Context, arg UpdateTechParams) (Tech, error)
	UpdateTown(ctx context.Context, arg UpdateTownParams) (Town, error)
	UpdateTraffic(ctx context.Context, arg UpdateTrafficParams) (Traffic, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error)
}

var _ Querier = (*Queries)(nil)
